#pragma once

#include "dep0/testing/ast_predicates/app.hpp"
#include "dep0/testing/ast_predicates/array.hpp"
#include "dep0/testing/ast_predicates/arith_expr.hpp"
#include "dep0/testing/ast_predicates/boolean_expr.hpp"
#include "dep0/testing/ast_predicates/constants.hpp"
#include "dep0/testing/ast_predicates/func_arg.hpp"
#include "dep0/testing/ast_predicates/global.hpp"
#include "dep0/testing/ast_predicates/init_list.hpp"
#include "dep0/testing/ast_predicates/pi.hpp"
#include "dep0/testing/ast_predicates/relation_expr.hpp"
#include "dep0/testing/ast_predicates/stmt.hpp"
#include "dep0/testing/ast_predicates/subscript.hpp"
#include "dep0/testing/ast_predicates/true_t.hpp"
#include "dep0/testing/ast_predicates/type_def.hpp"
#include "dep0/testing/ast_predicates/types.hpp"
#include "dep0/testing/ast_predicates/var.hpp"
