#define BOOST_TEST_MODULE dep0_parser_tests_0001_integral_primitives
#include <boost/test/unit_test.hpp>

#include "parser_tests_fixture.hpp"

BOOST_FIXTURE_TEST_SUITE(dep0_parser_tests_0001_integral_primitives, ParserTestsFixture)

BOOST_AUTO_TEST_CASE(pass_000) { BOOST_TEST(pass("0001_integral_primitives/pass_000.depc")); }

BOOST_AUTO_TEST_CASE(parse_error_000) { BOOST_TEST(fail("0001_integral_primitives/parse_error_000.depc")); }

BOOST_AUTO_TEST_CASE(typecheck_error_000) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_000.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_001) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_001.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_002) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_002.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_003) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_003.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_004) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_004.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_005) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_005.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_006) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_006.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_007) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_007.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_008) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_008.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_009) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_009.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_010) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_010.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_011) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_011.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_012) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_012.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_013) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_013.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_014) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_014.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_015) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_015.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_016) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_016.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_017) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_017.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_018) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_018.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_019) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_019.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_020) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_020.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_021) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_021.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_022) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_022.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_023) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_023.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_024) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_024.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_025) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_025.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_026) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_026.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_027) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_027.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_028) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_028.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_029) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_029.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_030) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_030.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_031) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_031.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_032) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_032.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_033) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_033.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_034) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_034.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_035) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_035.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_036) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_036.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_037) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_037.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_038) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_038.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_039) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_039.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_040) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_040.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_041) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_041.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_042) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_042.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_043) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_043.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_044) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_044.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_045) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_045.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_046) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_046.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_047) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_047.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_048) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_048.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_049) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_049.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_050) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_050.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_051) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_051.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_052) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_052.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_053) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_053.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_054) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_054.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_055) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_055.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_056) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_056.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_057) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_057.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_058) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_058.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_059) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_059.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_060) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_060.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_061) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_061.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_062) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_062.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_063) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_063.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_064) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_064.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_065) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_065.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_066) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_066.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_067) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_067.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_068) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_068.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_069) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_069.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_070) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_070.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_071) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_071.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_072) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_072.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_073) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_073.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_074) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_074.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_075) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_075.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_076) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_076.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_077) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_077.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_078) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_078.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_079) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_079.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_080) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_080.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_081) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_081.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_082) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_082.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_083) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_083.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_084) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_084.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_085) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_085.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_086) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_086.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_087) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_087.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_088) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_088.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_089) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_089.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_090) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_090.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_091) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_091.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_092) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_092.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_093) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_093.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_094) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_094.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_095) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_095.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_096) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_096.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_097) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_097.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_098) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_098.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_099) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_099.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_100) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_100.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_101) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_101.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_102) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_102.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_103) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_103.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_104) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_104.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_105) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_105.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_106) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_106.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_107) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_107.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_108) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_108.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_109) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_109.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_110) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_110.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_111) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_111.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_112) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_112.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_113) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_113.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_114) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_114.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_115) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_115.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_116) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_116.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_117) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_117.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_118) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_118.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_119) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_119.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_120) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_120.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_121) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_121.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_122) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_122.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_123) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_123.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_124) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_124.depc")); }
BOOST_AUTO_TEST_CASE(typecheck_error_125) { BOOST_TEST(pass("0001_integral_primitives/typecheck_error_125.depc")); }

BOOST_AUTO_TEST_SUITE_END()
